### PR TITLE
register detect public method

### PR DESCRIPTION
**Pull request by JoanClaret**
Defined `detect` public method in order to be able to use it in server side.

for instance:

```js
import bowser from 'bowser'
[...]
const ua = bowser.detect(userAgent)
domain.config('isMobile', ua.mobile)
[...]
```

i did not delete the private method because i don't know if this would break something.
let me know if it's fine for you, or we can do it in an other better way.
Cheeers
Joan

### CODE REVIEW

**Comment by lancedikson** [comment]
Hey, @JoanClaret. Sorry for being late. Thanks for the PR, I'll merge it now.

**Comment by lancedikson** [comment]
I just wasn't so sure if we need this since it's better to make a new version works ASAP. But, it's, of course, better to have some public detection method.

**Comment by lancedikson** [comment]
It's been released as 1.9.0.

**Comment by JoanClaret** [comment]
Great, thanks mate.

**Pull request closed without merging**
