### PR TITLE
fixing ES6 Module import for BROWSER_ALIAS_MAP

### PR DESCRIPTION
**Pull request by DasRed**

### CODE REVIEW

**Comment by lancedikson** [comment]
Hi, @DasRed. Could you please explain a bit why exactly we need these changes? I don't see any problem with having named exports for constants or, at least, it's not obvious :)

**Comment by DasRed** [comment]
> Hi, @DasRed. Could you please explain a bit why exactly we need these changes? I don't see any problem with having named exports for constants or, at least, it's not obvious :)

Hey @lancedikson,

the problem is the ES6 Module support. The package README.md contains following information:
     `import Bowser from "bowser"; // ES6`

But with the current code in src/constants.js is the use of ES6 Module not possible. The browser does not unterstand `module.exports`. You have to write `export ...` or `export default ... `.

And yes, following code is possible `export const BROWSER_ALIASES_MAP = {...};`.
Why i did not use it? There is only one constant exported, no other. So export it as default for easy using.

**Comment by lancedikson** [comment]
Oh, right. Good catch! We should change it. But, actually, I'd prefer not using `default` for it, but simply `export const BROWSER_ALIASES_MAP`, so that we could import it from the `constants` module by name like: `import { BROWSER_ALIASES_MAP } from '../constants'`

**Comment by DasRed** [comment]
> Oh, right. Good catch! We should change it. But, actually, I'd prefer not using `default` for it, but simply `export const BROWSER_ALIASES_MAP`, so that we could import it from the `constants` module by name like: `import { BROWSER_ALIASES_MAP } from '../constants'`

I have changed it to named export.

**Comment by lancedikson** [comment]
Now it's ESLint who is against the PR :) Please, ignore those `Prefer default export  import/prefer-default-export`, I have just changed them to be warnings instead of errors on the master branch. But, spaces before/after brackets are important.

**Comment by DasRed** [comment]
Really? Spaces? Okay... it is your project. I have added some spaces.

**Pull request merged**
