### PR TITLE
Support QQ Browser

### PR DESCRIPTION
**Pull request by mk-kialo**
This adds support for the QQ Browser (Windows, macOS, Android, iOS) and QQ Browser Lite a.k.a. QQ Browser for Mac (macOS). 

Note that the "Browser" in the name is relevant, as there is a different program called simply "QQ" (an instant messenger) which can also act as a browser.

### CODE REVIEW

**Comment by mk-kialo** [comment]
Well thank you! 🙌

**Comment by mk-kialo** [comment]
Hi @lancedikson! No pressure, just a little reminder for you and I hope that you will find the time to merge PRs soon. 😇I appreciate your work on this library. Thank you!

**Comment by lancedikson** [comment]
@mk-kialo, sorry, busy days. Will release it today, promise :)

**Comment by lancedikson** [comment]
Has been released as 2.7.0 :)

**Comment by mk-kialo** [comment]
Thanks a lot! 🙌

**Comment by weixublog** [comment]
in parser-browsers.js , QQ Browser named `QQ Browser Lite and 'QQ Browser`

but in constants.js，the BROWSER_ALIASES_MAP's key is `QQ and QQLite`

does it intentionally ?

**Comment by mk-kialo** [comment]
@weixublog yes! the browser aliases are just different names for the same thing, but shorter. See the other aliases defined such as `{samsung_internet: 'Samsung Internet for Android'}`.

**Comment by weixublog** [comment]
@mk-kialo 

in BROWSER_MAP
```
  qq: 'QQ Browser',
  qqlite: 'QQ Browser Lite',
  samsung_internet: 'Samsung Internet for Android',
```
but in it's aliases
```
  QQ: 'qq',
  QQLite: 'qqlite',
  'Samsung Internet for Android': 'samsung_internet',
```
it's different ...

maybe, we should use `QQ Browser Lite` as key , rather `QQLite` ?

**Pull request merged**
