### PR TITLE
Deploy docs to GH Pages

### PR DESCRIPTION
**Pull request by SterlingVix**
I noticed that the README promised a docs page soon, and that the docs pages worked, but just needed serving.

I added a `deploy` script which runs gh-pages: https://github.com/tschaub/gh-pages#command-line-utility

When you enter `npm run deploy` it will regenerate the docs and push to the `gh-pages` branch. The docs files are then visible at https://lancedikson.github.io/bowser/docs (also linked in README.md).

I hope this helps. :)

PS - I noticed I had a failing test during my local build, but I didn't touch any source code, so I assume that's a false negative.

### CODE REVIEW

**Comment by SterlingVix** [comment]
@lancedikson (or any other maintainers): any questions or feedback on this?

I maybe should have mentioned it in the commit: I tested the `gh-pages` script by deploying the docs on my fork. Literally all I did locally was run `npm run deploy`. What I got (and what you will get @ https://lancedikson.github.io/bowser/docs) is:

https://sterlingvix.github.io/bowser/docs

image

**Comment by lancedikson** [comment]
Hi, @SterlingVix. Sorry for the silence. Sounds great, but I didn't have a chance to have a look at it. I'll try to review and release it at the beginning of the week.

**Comment by SterlingVix** [comment]
Thanks @lancedikson , and no problem, of course. 😉 Please let me know if I can do anything to help.

**Comment by SterlingVix** [comment]
@lancedikson - I may not have been clear, but, as the repo owner, you'll have to run `npm run deploy` at least once to regenerate the docs and get them hosted on github.

Once you `npm run deploy`, then our `/docs` links should look essentially the same:
You: https://lancedikson.github.io/bowser/docs
Me: https://sterlingvix.github.io/bowser/docs/

My apologies if that wasn't clear in the PR.

**Comment by lancedikson** [comment]
@SterlingVix, thanks, but yeah, I know how it works, it's just hadn't enough time to make a release with proper changelogs and everything. Will do that today :) Sorry for the delay.

**Comment by SterlingVix** [comment]
No problem, hope I'm not bugging you! I'll leave it in your capable hands. 👍

**Pull request merged**
