### PR TITLE
Fix compatibility with Next.js middleware 

### LINKED ISSUE #512: Bowser crashes in Next.js Middleware Functions
While trying to use Bowser inside [`_middleware` Next.js Middleware Functions](https://nextjs.org/docs/advanced-features/middleware) (also Vercel doc - https://vercel.com/docs/concepts/functions/edge-functions/middleware)

`req.headers.get('user-agent')` of the browser is: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`

However the exception is thrown - 
```bash
error - (middleware)/node_modules/bowser/src/parser.js (95:0) @ eval
Error: Browser's test function is not valid
```

You can use official Vercel example to try it yourself - https://github.com/vercel/examples/blob/main/edge-functions/user-agent-based-rendering/pages/_middleware.ts

### PR DESCRIPTION
**Pull request by connor-baer**
Fixes #512.

### CODE REVIEW

**Review by voronianski — APPROVED** [review]

**Comment by zeckdude** [comment]
@connor-baer Thanks for the fix! I forked it and tested it and it looks like your solution needs to be applied on 4 more areas in the `parser.js` file where the `instanceOf` method is being used cause those are still currently not realizing that the test is an array.

@voronianski You may want to request changes so that gets addressed before merging.

**Review by zeckdude — CHANGES_REQUESTED** [review]
The fix to change the method to detect the array needs to be applied in 4 places for it to work in the Next.js middleware. Can you please make that fix?
Screen Shot 2022-07-11 at 4 55 17 PM

**Comment by connor-baer** [comment]
Good catch, @zeckdude! 

I think these code paths weren't reached in my testing, so the initial fix worked for my use case. Makes absolute sense to fix it everywhere though!

**Comment by zeckdude** [comment]
Vielen Dank!

**Review by zeckdude — APPROVED** [review]

**Comment by mkkhedawat** [comment]
Hey folks, I had forked https://github.com/mkkhedawat/frowser from this project recently given the inactivity from maintainer here. Would love to have this included in PR there if that is of interest.

**Review by naorpeled — APPROVED** [review]

**Pull request merged**
